export const ADMIN_REGISTER_REQUEST="ADMIN_REGISTER_REQUEST"
export const ADMIN_REGISTER_SUCCESS="ADMIN_REGISTER_SUCCESS"
export const ADMIN_REGISTER_FAIL="ADMIN_REGISTER_FAIL"

export const ADMIN_LOGOUT_SUCCESS="ADMIN_LOGOUT_SUCCESS"

export const ADMIN_LOGIN_REQUEST="ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS="ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL="ADMIN_LOGIN_FAIL"


export const CONDUCTOR_LOGIN_REQUEST="CONDUCTOR_LOGIN_REQUEST"
export const CONDUCTOR_LOGIN_SUCCESS="CONDUCTOR_LOGIN_SUCCESS"
export const CONDUCTOR_LOGIN_FAIL="CONDUCTOR_LOGIN_FAIL"

export const CONDUCTOR_REGISTRATION_REQUEST="CONDUCTOR_REGISTRATION_REQUEST"
export const CONDUCTOR_REGISTRATION_SUCCESS="CONDUCTOR_REGISTRATION_SUCCESS"
export const CONDUCTOR_REGISTRATION_FAIL="CONDUCTOR_REGISTRATION_FAIL"


export const GET_ADMINS_REQUEST="GET_ADMINS_REQUEST"
export const GET_ADMINS_SUCCESS="GET_ADMINS_SUCCESS"
export const GET_ADMINS_FAIL="GET_ADMINS_FAIL"


export const GET_ADMIN_REQUEST="GET_ADMIN_REQUEST"
export const GET_ADMIN_SUCCESS="GET_ADMIN_SUCCESS"
export const GET_ADMIN_FAIL="GET_ADMIN_FAIL"


export const DELETE_ADMIN_REQUEST="DELETE_ADMIN_REQUEST"
export const DELETE_ADMIN_SUCCESS="DELETE_ADMIN_SUCCESS"
export const DELETE_ADMIN_FAIL="DELETE_ADMIN_FAIL"


export const UPDATE_ADMIN_REQUEST="UPDATE_ADMIN_REQUEST"
export const UPDATE_ADMIN_SUCCESS="UPDATE_ADMIN_SUCCESS"
export const UPDATE_ADMIN_FAIL="UPDATE_ADMIN_FAIL"



export const GET_USERS_REQUEST="GET_USERS_REQUEST"
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const GET_USERS_FAIL="GET_USERS_FAIL"

export const DRIVER_LOGIN_REQUEST="DRIVER_LOGIN_REQUEST"
export const DRIVER_LOGIN_SUCCESS="DRIVER_LOGIN_SUCCESS"
export const DRIVER_LOGIN_FAIL="DRIVER_LOGIN_FAIL"

export const COMPANY_OWNER_LOGIN_REQUEST="COMPANY_OWNER_LOGIN_REQUEST"
export const COMPANY_OWNER_LOGIN_SUCCESS="COMPANY_OWNER_LOGIN_SUCCESS"
export const COMPANY_OWNER_LOGIN_FAIL="COMPANY_OWNER_LOGIN_FAIL"

export const COMPANY_OWNER_REGISTRATION_REQUEST="COMPANY_OWNER_REGISTRATION_REQUEST"
export const COMPANY_OWNER_REGISTRATION_SUCCESS="COMPANY_OWNER_REGISTRATION_SUCCESS"
export const COMPANY_OWNER_REGISTRATION_FAIL="COMPANY_OWNER_REGISTRATION_FAIL"


export const DRIVER_REGISTRATION_REQUEST="DRIVER_REGISTRATION_REQUEST"
export const DRIVER_REGISTRATION_SUCCESS="DRIVER_REGISTRATION_SUCCESS"
export const DRIVER_REGISTRATION_FAIL="DRIVER_REGISTRATION_FAIL"




export const GET_DRIVERS_REQUEST="GET_DRIVERS_REQUEST"
export const GET_DRIVERS_SUCCESS="GET_DRIVERS_SUCCESS"
export const GET_DRIVERS_FAIL="GET_DRIVERS_FAIL"

export const GET_DRIVER_REQUEST="GET_DRIVER_REQUEST"
export const GET_DRIVER_SUCCESS="GET_DRIVER_SUCCESS"
export const GET_DRIVER_FAIL="GET_DRIVER_FAIL"


export const UPDATE_DRIVER_REQUEST="UPDATE_DRIVER_REQUEST"
export const UPDATE_DRIVER_SUCCESS="UPDATE_DRIVER_SUCCESS"
export const UPDATE_DRIVER_FAIL="UPDATE_DRIVER_FAIL"

export const DELETE_DRIVER_REQUEST="DELETE_DRIVER_REQUEST"
export const DELETE_DRIVER_SUCCESS="DELETE_DRIVER_SUCCESS"
export const DELETE_DRIVER_FAIL="DELETE_DRIVER_FAIL"

export const DELETE_CONDUCTOR_REQUEST="DELETE_CONDUCTOR_REQUEST"
export const DELETE_CONDUCTOR_SUCCESS="DELETE_CONDUCTOR_SUCCESS"
export const DELETE_CONDUCTOR_FAIL="DELETE_CONDUCTOR_FAIL"


export const GET_CONDUCTORS_REQUEST="GET_CONDUCTORS_REQUEST"
export const GET_CONDUCTORS_SUCCESS="GET_CONDUCTORS_SUCCESS"
export const GET_CONDUCTORS_FAIL="GET_CONDUCTORS_FAIL"

export const GET_CONDUCTOR_REQUEST="GET_CONDUCTOR_REQUEST"
export const GET_CONDUCTOR_SUCCESS="GET_CONDUCTOR_SUCCESS"
export const GET_CONDUCTOR_FAIL="GET_CONDUCTOR_FAIL"


export const GET_CONDUCTOR_TRIPS_REQUEST="GET_CONDUCTOR_TRIPS_REQUEST"
export const GET_CONDUCTOR_TRIPS_SUCCESS="GET_CONDUCTOR_TRIPS_SUCCESS"
export const GET_CONDUCTOR_TRIPS_FAIL="GET_CONDUCTOR_TRIPS_FAIL"


export const GET_DRIVER_TRIPS_REQUEST="GET_CONDUCTOR_TRIPS_REQUEST"
export const GET_DRIVER_TRIPS_SUCCESS="GET_CONDUCTOR_TRIPS_SUCCESS"
export const GET_DRIVER_TRIPS_FAIL="GET_CONDUCTOR_TRIPS_FAIL"


export const UPDATE_CONDUCTOR_REQUEST="UPDATE_CONDUCTOR_REQUEST"
export const UPDATE_CONDUCTOR_SUCCESS="UPDATE_CONDUCTOR_SUCCESS"
export const UPDATE_CONDUCTOR_FAIL="UPDATE_CONDUCTOR_FAIL"



export const RESET_ERROR='RESET_ERROR';