
export const ADD_COMPANY_REQUEST="ADD_COMPANY_REQUEST"
export const ADD_COMPANY_SUCCESS="ADD_COMPANY_SUCCESS"
export const ADD_COMPANY_FAIL="ADD_COMPANY_FAIL"
export const GET_COMPANY_REQUEST="GET_COMPANY_REQUEST"
export const GET_COMPANY_SUCCESS="GET_COMPANY_SUCCESS"
export const GET_COMPANY_FAIL="GET_COMPANY_FAIL"

export const GET_COMPANIES_REQUEST="GET_COMPANIES_REQUEST"
export const GET_COMPANIES_SUCCESS="GET_COMPANIES_SUCCESS"
export const GET_COMPANIES_FAIL="GET_COMPANIES_FAIL"