
export const GET_TRIPS_REQUEST="GET_TRIPS_REQUEST"
export const GET_TRIPS_SUCCESS="GET_TRIPS_SUCCESS"
export const GET_TRIPS_FAIL="GET_TRIPS_FAIL"


export const GET_TRIP_REQUEST="GET_TRIP_REQUEST"
export const GET_TRIP_SUCCESS="GET_TRIP_SUCCESS"
export const GET_TRIP_FAIL="GET_TRIP_FAIL"


export const ADD_TRIP_REQUEST="ADD_TRIP_REQUEST"
export const ADD_TRIP_SUCCESS="ADD_TRIP_SUCCESS"
export const ADD_TRIP_FAIL="ADD_TRIP_FAIL"



export const EDIT_TRIP_REQUEST="EDIT_TRIP_REQUEST"
export const EDIT_TRIP_SUCCESS="EDIT_TRIP_SUCCESS"
export const EDIT_TRIP_FAIL="EDIT_TRIP_FAIL"


export const GET_USER_TRIP_REQUEST="GET_USER_TRIP_REQUEST"
export const GET_USER_TRIP_SUCCESS="GET_USER_TRIP_SUCCESS"
export const GET_USER_TRIP_FAIL="GET_USER_TRIP_FAIL"

export const ADD_PASSENGER_REQUEST="ADD_PASSENGER_REQUEST"
export const ADD_PASSENGER_SUCCESS="ADD_PASSENGER_SUCCESS"
export const ADD_PASSENGER_FAIL="ADD_PASSENGER_FAIL"


export const CANCEL_TRIP_REQUEST="CANCEL_TRIP_REQUEST"
export const CANCEL_TRIP_SUCCESS="CANCEL_TRIP_SUCCESS"
export const CANCEL_TRIP_FAIL="CANCEL_TRIP_FAIL"

export const SEND_DATA_TO_API='SEND_DATA_TO_API'


export const DELETE_TRIP_REQUEST="DELETE_TRIP_REQUEST"
export const DELETE_TRIP_SUCCESS="DELETE_TRIP_SUCCESS"
export const DELETE_TRIP_FAIL="DELETE_TRIP_FAIL"




export const GET_PASSENGERS_REQUEST="GET_PASSENGERS_REQUEST"
export const GET_PASSENGERS_SUCCESS="GET_PASSENGERS_SUCCESS"
export const GET_PASSENGERS_FAIL="GET_PASSENGERS_FAIL"


